#-------------------------------
# Site Settings
title: Pedro Revueltas
logo: # You can add own logo. For example '/images/logo.png'.
description: Blog personal de Pedro Revueltas
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pedrorevueltas.com" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: dark # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Author Settings
author:
  author__name: Pedro Revueltas
  author__bio: 'Software Development Manager con una misi칩n: lograr que equipos de alto voltaje desarrollen productos digitales asombrosos.'
  author__avatar: '/images/pedro-revueltas-perfil.jpg'

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/pedrorevueltas"}
# - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# - {icon: "ion-logo-instagram", link: "https://instagram.com"}
# - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# - {icon: "ion-logo-youtube", link: "https://youtube.com"}
- {icon: "ion-logo-github", link: "https://github.com/prevueltas"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/pedrorevueltas/"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  hero__title: Hola! Soy Pedro Revueltas
  hero__description: Me dedico a gestionar y, muchas veces, liderar, equipos de desarrollo software, grandes o peque침os, pero siempre con un gran prop칩sito.
  hero__image: '/images/foto-pedro-revueltas-portatil.jpg'


#-------------------------------
# Newsletter
mailchimp: # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text: Subscribe here
mailchimp__button__text: Get a new tip


#-------------------------------
# Gallery Footer Section
gallery:
  gallery__title: Algunas fotos
  gallery__columns: 3
  gallery__images:
    - alt: 'Desktop setup'
      url: '/images/gallery/pedro-setup.jpg'
    - alt: 'Asistentes a la CAS'
      url: '/images/gallery/charla-cas-asistentes.jpg'
    - alt: 'Portada charla CAS'
      url: '/images/gallery/charla-cas-inicio.jpg'
    - alt: 'Din치mica equipo'
      url: '/images/gallery/dinamica-equipo.jpg'
    - alt: 'Enemigo invisible por Navidad'
      url: '/images/gallery/enemigo-invisible.jpg'
    - alt: 'Equipo PRISA'
      url: '/images/gallery/equipo-prisa.jpg'
    - alt: 'Openspace'
      url: '/images/gallery/foto-adri-pedro.jpg'
    - alt: 'Formacion Paradigma Institude'
      url: '/images/gallery/pedro-formacion.jpg'
    - alt: 'Formacion Paradigma Institute Java'
      url: '/images/gallery/pedro-formacion-2.jpg'
    - alt: 'Tabler User Story Map'
      url: '/images/gallery/tablero.jpg'
    - alt: 'Carrera de Empresas'
      url: '/images/gallery/carrera-empresas.jpg'
    - alt: 'Stand up meeting en Skylab, Manchester'
      url: '/images/gallery/last-standup-skylab.jpg'

#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your email for contant form
  description: Menso comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Menso theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example demo-menca


#-------------------------------
# Google Analytics
google-analytics: G-D84BY9YRSZ # Add your GA Tracking Id


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed